@startuml
actor Public_User as PU
actor User as U
actor Admin as A

PU --> (See Detail of Concert)
U --> (See Detail of Concert)
U --> (Reserve Concert)
U --> (Cancel Reserve Concert)
A --> (Create Concert)
A --> (Update Concert)
A --> (Delete Concert)
A --> (See Detail of Concert)

@enduml
