@startuml
actor Public_User as PU
actor User as U
actor Admin as A

A --> (See Summary)
A --> (See Detail of Concerts)
A --> (Delete Concert)
A --> (Create Concert)
A --> (Concert Reservation History )


PU --> (See Detail of Concerts)

U --> (See Detail of Concerts)
U --> (Reserve Concert)
U --> (Cancel Reserve Concert)
U --> (Concert Own Reservation History)


@enduml
